### ISSUE TITLE
Netlify adapter suggests an incorrect link

### ISSUE THREAD

**Issue by ematipico** [withastro/adapters#115]
### Astro Info

```block
Astro                    v4.0.7
Node                     v18.15.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/netlify
Integrations             @astrojs/react
                         @astrojs/starlight
```

### Describe the Bug

This bug 

```
[AstroUserError] config.image.domains and config.image.remotePatterns aren't supported by the Netlify adapter.
  Hint:
    See https://github.com/withastro/adapters/tree/main/packages/netlify#image-cdn for more.
  Stack trace:

```

Points to an URL that doesn't exist in the README.md

### What's the expected result?

It should point to https://github.com/withastro/adapters/tree/main/packages/netlify#netlify-image-cdn-support

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
It should probably not point to the README anymore, since that page was moved to the https://github.com/withastro/docs/pull/5839 repo.
