### ISSUE TITLE
Netlify adapter, can't opt out image service 

### ISSUE THREAD

**Issue by ematipico** [withastro/adapters#118]
### Astro Info

```block
main
```

### Describe the Bug

The new version of Netlify adapter doesn't allow to opt out of the image service used by Netlify.

### What's the expected result?

Like the Vercel adapter, I would expect an option, because the Netlify image service doesn't support remote patterns **out of the box**.

### Link to Minimal Reproducible Example

None

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
I agree, having a option to opt-in / opt-out would be preferable.

cc @Skn0tt

**Comment by Skn0tt** [comment]
Agreed! I'll work on this.

**Comment by Skn0tt** [comment]
Here's the PR: https://github.com/withastro/adapters/pull/120
