### ISSUE TITLE
Unable to route to API using Netlify adapter

### ISSUE THREAD

**Issue by Xypter** [withastro/adapters#126]
### Astro Info

```block
Astro                    v4.1.0
Node                     v20.10.0
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/netlify
Integrations             none
```

### Describe the Bug

I am having an issue with the Netlify adapter.

I am deploying my Astro front end with SSR enabled using continual deployment from my [Github repository](https://github.com/Xypter/sgxp). For the back-end I have an API created in Strapi I am hosting on Digital Ocean.

I created an `[id].astro` page in the [pages directory](https://github.com/Xypter/sgxp/blob/master/visible-venus/src/pages/sheets/%5Bid%5D.astro) and a fetch API on the same page which allows me to look up an object in my array by ID and dynamically put the ID in the link. So far it is working fine on localhost, but does not work when I deploy the site to Netlify. [Here is what my Astro.config.mjs looks like](https://github.com/Xypter/sgxp/blob/master/visible-venus/astro.config.mjs)

### What's the expected result?

On localhost when I call the API, it gives me an ID, then routes the page to that ID (in my case, the path should be going to /sheets/[id]. When deployed on Netlify however, it throws me a 404 page.

I was also following the steps of [this](https://astro.build/blog/netlify-edge-functions/) article, but it seems the information is out of date since Astro throws an error when you attempt to include `import netlify from "@astrojs/netlify/edge-functions"`. For now I have left that line as `import netlify from '@astrojs/netlify';`.

### Link to Minimal Reproducible Example

https://sgxp.me/sprites

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Skn0tt** [comment]
> I was also following the steps of [this](https://astro.build/blog/netlify-edge-functions/) article, but it seems the information is out of date

Good catch! Looks like we need to update that. This seems to be the underlying file: 
https://github.com/withastro/astro.build/blob/main/src/content/blog/netlify-edge-functions.mdx - i'll open a PR with a change, cc @sarah11918.

**Comment by Skn0tt** [comment]
> When deployed on Netlify however, it throws me a 404 page.

Thanks for providing the reproduction repo. I'll try deploying that to my account and will check if I can reproduce what you're seeing!

**Comment by Skn0tt** [comment]
> i'll open a PR with a change

I'll have to walk back on that. It looks like said blog post talks about running SSR within Edge Functions, which the new Adapter doesn't support anymore. So the whole blog post is outdated, essentially. @sarah11918 what's the best way to change that? Could we add a callout to the post?

**Comment by Skn0tt** [comment]
I've deployed the `visible-venus` directory in your repo to `https://splendorous-daifuku-60b64e.netlify.app`, and here's what i'm seeing:

```sh
❯ curl -v https://splendorous-daifuku-60b64e.netlify.app/sheets/foo
...
< HTTP/2 302 
< age: 0
< cache-control: no-cache
< cache-status: "Netlify Edge"; fwd=miss
< date: Mon, 08 Jan 2024 13:46:45 GMT
< location: /404
```

this matches the redirect in your try/catch:

https://github.com/Skn0tt/sgxp/blob/15ad7cc1bf8b4b6c0fbe1fb4ad3d19fa4095a35e/visible-venus/src/pages/sheets/%5Bid%5D.astro#L18-L20

So it looks like the site is doing what's in the code. @Xypter does this help? Is there some other issue at play here, that i'm not seeing?

**Comment by Xypter** [comment]
@Skn0tt Thanks for your help. I feel dumb, as I realized looking back into my code again that I was using an environment variable in my [strapi.ts endpoint url on line 26](https://github.com/Xypter/sgxp/blob/master/visible-venus/lib/strapi.ts), which I had not imported into Netlify yet. After doing so, everything resolved!

If nothing else, I hope opening this issue to point out the outdated blog was helpful.

**Comment by Skn0tt** [comment]
No worries, stuff like this always happens to me before the first coffee! :D
