### ISSUE TITLE
External rewrites do not work on Netlify

### ISSUE THREAD

**Issue by florian-lefebvre** [withastro/adapters#140]
### Astro Info

```block
Astro                    v4.2.4
Node                     v18.19.0
System                   Windows (x64)
Package Manager          yarn
Output                   hybrid
Adapter                  @astrojs/netlify
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

When having such a rewrite inside `public/_redirects`, it just does not work. It used to work in v3:

```
/test https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js 200!
```

See https://65b26bfaede6390008a7ac7a--splendid-youtiao-ce6c96.netlify.app/test

### What's the expected result?

The rewrite should work, not return a 404.

### Link to Minimal Reproducible Example

https://github.com/florian-lefebvre/astro-netlify-redirects-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Skn0tt** [comment]
Hey Florian, thanks for providing a repro! I'll take a look if I can spot what's going on.

**Comment by Skn0tt** [comment]
What seems to be happening is that the `_redirect` is shadowed by the SSR function. This seems to be a bug in the routing of Netlify Functions 2.0, which the v4 of the adapter uses. I've opened a tracking issue internally and submitted a fix, will report back here when it's deployed.

**Comment by florian-lefebvre** [comment]
Awesome thank you!

**Comment by jimAScott** [comment]
Hi @Skn0tt,

We also have this issue after upgrading from V3 which is preventing us from deploying the latest version of package. 
Any update on when this may be fixed would be gratefully received. 

Happy to test a fix on our environment if that helps.

**Comment by spacedawwwg** [comment]
> Hi @Skn0tt,
> 
> We also have this issue after upgrading from V3 which is preventing us from deploying the latest version of package. Any update on when this may be fixed would be gratefully received.
> 
> Happy to test a fix on our environment if that helps.

+1

**Comment by Skn0tt** [comment]
Thanks y'all for posting in here, this makes it easier for me to prioritise this. As an update, we rolled out a fix around our routing logic for Functions 2.0 (used by v4 of this adapter) that should've solved this. Now that i'm verifying it end-to-end it apparently isn't enough yet - so I need to do more investigation. A fix is in the works!

**Comment by Skn0tt** [comment]
Ha, it did work - I just tested it in the wrong way. https://65b26bfaede6390008a7ac7a--splendid-youtiao-ce6c96.netlify.app/test is now returning the proxie'd mixpanel script, as it should. This fix is rolled out to all non-enterprise customers at Netlify now, and will go to enterprise customers in a couple days. Let me know if y'all are seeing it fixed as well :)

**Comment by florian-lefebvre** [comment]
Thanks for the quick response! I didn't know that it could be considered illegal, as long as no personal data is gathered. Good to know!

**Comment by spacedawwwg** [comment]
@Skn0tt does that mean we can update our adapter now?

**Comment by Skn0tt** [comment]
If you're not on the Enterprise tier, yes you can! Ideally, you can double check if everything works alright using a Deploy Preview, and then merge the adapter update if things are looking good.

**Comment by spacedawwwg** [comment]
> If you're not on the Enterprise tier, yes you can! Ideally, you can double check if everything works alright using a Deploy Preview, and then merge the adapter update if things are looking good.

We are Enterprise tier

**Comment by Skn0tt** [comment]
Gotcha! I'll advance the rollout to Enterprise early next week and let you know once that's done.

**Comment by spacedawwwg** [comment]
Thanks @Skn0tt

**Comment by Skn0tt** [comment]
Advanced to Enterprise. Try it out and let me know if there's anything else missing for you to migrate!

**Comment by spacedawwwg** [comment]
@Skn0tt this has fixed it for us! v5.0.1 is a thumbs up

**Comment by Skn0tt** [comment]
Lovely! Then I guess this issue can be closed :D

**Comment by spacedawwwg** [comment]
@Skn0tt this issue has reared it's head again
<img width="1793" alt="image" src="https://github.com/withastro/adapters/assets/1691867/b80826f7-b58e-4883-b010-d7371c33c4d2">

**Comment by Skn0tt** [comment]
Looks like Art, if you ask me.

**Comment by Skn0tt** [comment]
Jokes aside, what makes you think this is related to external rewrites?

**Comment by spacedawwwg** [comment]
@Skn0tt As the netlify **REAL** URL's are working (e.g stage-netlify.ourdomain.com) but our redirected domains (e.g stage.ourdomain.com) blows up with the above

**Comment by Skn0tt** [comment]
Glad you found a fix! :D

**Comment by spacedawwwg** [comment]
> Glad you found a fix! :D

@Skn0tt No fix found yet, but as we're enterprise Netlify customers your devs, who are much smarter than me, are helping us track down the issue. Its something about the request getting two different responses:

> one says: initial="deflate, gzip, br, zstd" (this works) and the other one says initial=gzip (this is the one that gives the issue). I can also see that HTTP2 gets converted to HTTP 1.1.
