### ISSUE TITLE
☂️ Move Adapters tests to `node:test`

### ISSUE THREAD

**Issue by alexanderniebuhr** [withastro/adapters#144]
## Description

Internally, the team decided to move our testing infrastructure to use `node:test` instead of Mocha.

While Mocha **is good**, it has its own quirks. Also, we believe that the Node.js test runner will improve with time. 

This is an **excellent opportunity** to contribute to Astro and help us with the migration because you don't need to understand Astro logic. So if you have been looking for an opportunity to contribute to Astro, this is the **perfect chance for you**!

## Plan

**Comment here which integration/adapter** you want to migrate first. Failing to comment might nullify your contribution if someone else did the work and **commented** on the issue. This will help us to avoid having multiple people working on the same thing.

The plan should be as follows:
1. Migrate tests of our `@astrojs/*` packages. You can use this PR as a blueprint of what we're looking for, **however this repository might be a little different, so this can only be used as a reference:** https://github.com/withastro/astro/pull/9758

### Integrations/adapters

List of the integrations/adapters

- [x] Migrate tests of [`@astrojs/cloudflare`](https://github.com/withastro/adapters/tree/main/packages/cloudflare)
- [x] Migrate tests of [`@astrojs/netlify`](https://github.com/withastro/adapters/tree/main/packages/netlify)

**Comment by xMohamd** [comment]
I migrate tests of [@astrojs/cloudflare](https://github.com/withastro/adapters/tree/main/packages/cloudflare)
but when I tried to  `pnpm run test` after edited  `package.json` with next command it , it gives me that error.
`test": "astro-scripts test --timeout 3000 \"test/**/*.test.js\"`

```
 pnpm run test

> @astrojs/cloudflare@9.0.0 test C:\Users\Username\Desktop\astro-adapters\packages\cloudflare
> astro-scripts test --timeout 30000 "test/**/*.test.js"

'astro-scripts' is not recognized as an internal or external command,
operable program or batch file.
 ELIFECYCLE  Test failed. See above for more details.
```
I tried to fix it, but I couldn't,

**Comment by alexanderniebuhr** [comment]
@xMohamd Thank you. We are not using `astro-scripts` in this repository. So instead of calling that, we should call `node` directly. I really would appreciate if you already open a PR with the changes you have so far, and I could look into the error, if you want :)

**Comment by abidjappie** [comment]
I'd like to try migrating the tests for @astrojs/netlify 🙇

**Comment by xMohamd** [comment]
> @xMohamd Thank you. ❤️
> 
> We are not using `astro-scripts` in this repository. So instead of calling that, we should call `node` directly. I really would appreciate if you already open a PR with the changes you have so far, and I could look the fix for the Error, if you want :)

@alexanderniebuhr #150 Check it and let me know if there is any issue

**Comment by alexanderniebuhr** [comment]
Thank you everyone for all contributions! ❤️
