### ISSUE TITLE
Netlify request vs run time

### ISSUE THREAD

**Issue by ofrades** [withastro/adapters#145]
### Astro Info

```block
Astro                    v4.2.7
Node                     v18.18.2
System                   Linux (x64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/netlify
Integrations             @astrojs/starlight
                         @astrojs/tailwind
                         @astrojs/react
```

### Describe the Bug

I have deployed an hybrid app yesterday and I have reached the max number of requests per function in netlify with zero runtime seconds, how is this even possible?

Other considerations: 
my use base is around 100 users per day, we can discard the possibility of that many number of users;
the requests numbers jump around 20.000 each time. My app has approximately that number of files, which are consumed by the only function I have. Can that be the problem?  

![image](https://github.com/withastro/adapters/assets/31070771/456829cd-ffe8-446c-a166-b60895ce7a78)

### What's the expected result?

I would expect to have a 1000 max requests per day.

### Link to Minimal Reproducible Example

https://github.com/tesourofieis/tesourofieis

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Skn0tt** [comment]
Hmm, that's interesting. This definitely doesn't look right, i've kicked off an investigation internally at Netlify.

**Comment by ofrades** [comment]
Thanks @Skn0tt . I've not added a minimal example, but I added the app that is causing this issue.

**Comment by Skn0tt** [comment]
Hey @ofrades, just as an update: We're still investigating this. I can confirm that your site didn't execute this many Functions. Could you open a support case with us at https://www.netlify.com/support/#contact, and briefly mention this issue in it?

**Comment by Skn0tt** [comment]
Okay, we found out why it doesn't show the run time and are working on a fix. Interestingly, looking deeper it appears that your site (until you deployed an update) indeed did execute that many functions. The top user agent for them is `node`, and the IP addresses for it seem to be coming from within Netlify Functions. They also all result in 404 responses! This feels related to #133. I have a hunch that the Astro rendering runtime is making a request to itself, resulting in an infinite loop that drives up your request numbers. I'll be verifying this now.

It looks like you've already worked around this in some way. I believe that https://github.com/withastro/adapters/pull/143 will fix this issue. Another workaround is that you set `export prerender = false` on your custom 404 page.

**Comment by Skn0tt** [comment]
I've asked internally to make sure that you're not billed for these overage executions. If that doesn't end up working because it's too late (we're right on the month change!), please let me know and i'll make sure you're refunded.

**Comment by ofrades** [comment]
Thank you very much @Skn0tt 

Probably I will not be charged because I did not set my credit card details, but if netlify reaches out I will let know.

I ended up using astro static mode only, but in the near future I might give ssr another try, thanks.

**Comment by Skn0tt** [comment]
Sounds good! I've surfaced this with our support team, and they mentioned that you might have to manually downgrade to "functions level 0" now that you're not executing that many functions anymore. Otherwise, you'll have an unpaid bill for that every month, and I'm not sure how nice our systems are about that 😅 Sorry for the trouble again!
