### ISSUE TITLE
Astro Cloudflare - Error: Failed to publish your Function. Got error: Error 8000057: Rules in `_routes.json` are over the 100 rule limit.

### ISSUE THREAD

**Issue by whoiscarlo** [withastro/adapters#146]
### Astro Info

```block
Astro                    v4.3.0
Node                     v20.6.1
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/solid-js
                         @astrojs/tailwind
```

### Describe the Bug

Hey, I'm building an Astro site with server side rendering using Cloudflare Pages with server side rendering with the following dynamic paths:
`/car/[colorId].astro`
`/[users]/index.astro`

and when I submit to workers I get this error and a failed deployment. 

https://github.com/withastro/adapters/issues/135#issuecomment-1919692162

```
08:49:49.373 | Found _worker.js in output directory. Uploading.
-- | --
08:49:50.846 | ✨ Compiled Worker successfully
08:49:50.895 | Found _routes.json in output directory. Uploading.
08:49:50.910 | Validating asset output directory
08:49:51.627 | Deploying your site to Cloudflare's global network...
08:49:56.287 | Uploading... (353/422)
08:49:57.090 | Uploading... (376/422)
08:49:57.218 | Uploading... (399/422)
08:49:57.550 | Uploading... (422/422)
08:49:57.550 | ✨ Success! Uploaded 69 files (353 already uploaded) (1.72 sec)
08:49:57.550 |  
08:49:58.142 | ✨ Upload complete!
08:50:01.603 | Success: Assets published!
08:50:09.419 | Error: Failed to publish your Function. Got error: Error 8000057: Rules in `_routes.json` are over the 100 rule limit. Refer to https://cfl.re/3FsE4aF.
```

### What's the expected result?

A successful deployment with a working site.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7e2amg?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by whoiscarlo** [comment]
> Please try to see if this option helps
> 
> https://docs.astro.build/en/guides/integrations-guide/cloudflare/#routesstrategy

So I added the following and still seeing the error. Did I set it up incorrectly? And I don't fully understand want this means

> // handled by custom function: functions/users/[id].js

I don't have a `functions` directory in my project will that then cause a problem?

```
adapter: cloudflare({
		imageService: 'cloudflare', // 'cloudflare' or 'imgix'
		mode: 'directory',
		routes: {
			strategy: 'include',
			include: ['/car/*', '/[users]/'], 
			exclude: ['/car'], 
		},
	})
```

**Comment by alexanderniebuhr** [comment]
You just need the 'strategy' setting. You can try to use 'exclude'.

If that doesn't help, I would like to ask for a reproduction example.

**Comment by whoiscarlo** [comment]
@alexanderniebuhr thank you for you help! I ended using this and all is now well 🥳

```
export default defineConfig({
	integrations: [solidJs(), tailwind()],
	output: "server",
	adapter: cloudflare({
		mode: 'directory',
		functionPerRoute: true,
	}),
});
```

**Comment by whoiscarlo** [comment]
@alexanderniebuhr thank you for you help! I ended using this and all is now well 🥳

```
export default defineConfig({
	integrations: [solidJs(), tailwind()],
	output: "server",
	adapter: cloudflare({
		mode: 'directory',
		functionPerRoute: true,
	}),
});
```

**Comment by aqueenan** [comment]
The `include` array needs to include all of the pages and server api, and the `exclude` array needs to include the list of static assets in `public`.

The easiest way of doing that is to exclude everything in `public`, plus the generated code in `_astro`. My `public` folder has a bunch of icon files (matching `*.*`) and subfolders for `images` and `plugins`, so I exclude them all with:

```
  adapter: cloudflare({
    routes: {
      "exclude": [
        "/*.*",
        "/_astro/*",
        "/images/*",
        "/plugins/*",
      ],
    }
```
