### ISSUE TITLE
Cloudflare adapter i18ndomains error with Astro 4.3

### ISSUE THREAD

**Issue by alexturpin** [withastro/adapters#148]
### Astro Info

```block
Astro                    v4.3.0
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/react
```

### Describe the Bug

The following errors occur on startup with the new Astro 4.3 i18nDomains feature

```
14:36:48 [ERROR] [config] The feature "i18nDomains" is not supported (used by @astrojs/cloudflare).
14:36:48 [ERROR] The adapter @astrojs/cloudflare doesn't support the feature i18nDomains. Your project won't be built. You should not use it.
```

### What's the expected result?

A project not using `i18nDomains` should still work on the Cloudflare adapter

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-k3ev6s?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
Thanks. IIRC this is only a warning and you are still able to use the Cloudflare adapter.
However this should be fixed once https://github.com/withastro/astro/pull/9932 is merged and released
