### ISSUE TITLE
[Cloudflare adapters] Possible bug: too many _routes.json entries

### ISSUE THREAD

**Issue by maddsua** [withastro/adapters#172]
### Astro Info

```block
Astro                    v4.4.1
Node                     v20.9.0
System                   Windows (x64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/sitemap
                         @astrojs/vue
                         @astrojs/tailwind
```

### Describe the Bug

Setup: a project with cloudflare adapter in hybrid mode and routes strategy set to "include".

```typescript
output: 'hybrid',
adapter: cloudflare({
  imageService: 'passthrough',
  routes: {
    strategy: 'include',
    include: [
      '/store/item/configure',
      '/api/*',
    ]
  }
})
 ```

By the very definition it should only include entries for what I specified manually, but instead it creates more than 100 records that look like this:
```json
{
  "version": 1,
  "include": [
    "/*",
    "/api/*",
    "/*/store/item/configure"
  ],
  "exclude": [
    "/",
    "/uk/",
    "/ru/",
    "/pl/",
    "/de/",
    "/404.html",
    "/index.html",
    "..."
  ]
}
```

Why is this a problem? Cloudflare refuses to deploy a project and returns this error:
> Invalid _routes.json file found at: dist/_routes.json
  Overlapping rules found. Please make sure that rules ending with a splat (eg. "/api/*") don't overlap any other rules (eg. "/api/foo"). This applies to both include and exclude rules individually.

Btw: Astro is broken on stackblitz again, it just doesn't build xD

### What's the expected result?

It's not necesary to add anything to the exclude patterns list and that "/*" at the start of includes is not needed there either.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8ty8mk

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by maddsua** [comment]
For now I'm just gonna use a manually generated routes files, but this needs to be fixed, and I think I can take care of this bug if the team gives a green light

**Comment by alexanderniebuhr** [comment]
@maddsua Thank you for the report. Just to let you know the `routes.include`, `routes.exclude` options do extend the _routes.json and don't replace them. So it is correct that you get more than definitions than the one you define in your adapter options. If you want fully manual control over the _routes.json file, the correct way is to have your own file in the `public` folder.

If you still think there is an issue, in the outlined behaviour from me above, we are happy for you to try fix that and submit a PR for review.

**Comment by maddsua** [comment]
@alexanderniebuhr Thanks for responding! Good to know that those parameters extend `_routes.json` and not overwrite it, but I have a completely empty `_routes.json` file (I don't have it at all to be exact) and just using `routes.include` causes cloudflare to reject the upload.

In my config, this is literally all that I put into it:
```javascript
include: [
  '/store/item/configure',
  '/api/*',
]
```

Just 2 paths, and for some reason it adds `/*` to that and then proceeds to list all the routes that should be excluded from this pattern. For the reference, this is what valid `_routes.json` looks like for this app:

```json
{
  "version": 1,
  "include": [
    "/api/*",
    "/store/item/configure"
  ],
  "exclude": []
}
```

**Comment by maddsua** [comment]
Umm, I have `routes.strategy` set to `include`, that's why I created this issue.

I'm gonna quone the comment line for this options:
> For each page that is prerendered and whoose path is matched by an `include` entry, an entry in the `exclude` array will be generated.

Problem is, for whatever reason a `/*` entry gets added to the top of the `include` list which causes the creation of that huge `exclude` list and sub sequentially deploy failure

**Comment by maddsua** [comment]
I gonna jump to the code real quick, but it seems like there was an oopsie and `/*` insertion just doesn't get disabled for `include` strategy

**Comment by maddsua** [comment]
From what I learned so far, this edge case is caused by a `/[...api].ts` route existing in a project. Ok, fair enuff, but why isn't this behavior also caused by `/[...index].astro` 🤔

**Comment by maddsua** [comment]
But I guess I have a new issue now =)
