### ISSUE TITLE
Service bindings in the Cloudflare adapter

### ISSUE THREAD

**Issue by F0rce** [withastro/adapters#175]
### Astro Info

```block
Astro                    v4.4.6
Node                     v20.10.0
System                   macOS (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

Currently the `@astrojs/cloudflare` adapter does not support [Service bindings](https://developers.cloudflare.com/workers/configuration/bindings/about-service-bindings/). 

### What's the expected result?

[Service bindings](https://developers.cloudflare.com/workers/configuration/bindings/about-service-bindings/) are a crucial part if you want to call a worker from the *server side* part of a page if they are hosted on the same domain (and the worker uses a worker route). I already had a bigger conversation with Cloudflare and even had a post on the forum explaining everything ([reference](https://community.cloudflare.com/t/requesting-worker-from-pages-on-same-domain/621315)). I would really appreciate if the adapter would have the ability to request a worker through a service binding.

I'm willing to submit a pull request for this issue if I'm assisted in some sort of way :)

Thanks a lot,
David

### Link to Minimal Reproducible Example

https://developers.cloudflare.com/workers/configuration/bindings/about-service-bindings/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by F0rce** [comment]
**Just for clarification:**

Service bindings work totally fine when deployed to Cloudflare and setup via the Dashboard. This "feature" is more like for development purposes, especially because miniflare can do that.

**Comment by alexanderniebuhr** [comment]
Thanks for opening the issue. We are happy to get contributions for this. We will hopefully don't need this anymore with the upcoming v10, but for v9 it still would be great to have it added.

**Comment by F0rce** [comment]
Thanks for the answer @alexanderniebuhr 

Is there any way I could assist with implementing it for v9 (I'm already playing around locally) or better said is it already implemented in v10 for me to test out?

If wanted we could also transfer this "ping pong" to discord, that this issue is as clean as it is.

**Comment by alexanderniebuhr** [comment]
If you would be open for a PR, please feel free to create one. It should be as simple as adding the options to the config and then passing it to the Miniflare instance _(I guess)_.. If you have any question feel free to ping me in Discord.

V10 does not has it implemented yet, and I don't suggest doing it for v10 yet.. If we pull it off that v10 uses `workerd` natively, it will support everything Miniflare does out-of-the-box :)
