### ISSUE TITLE
Bug: Astro.locals.netlify is untyped

### ISSUE THREAD

**Issue by nickytonline** [withastro/adapters#189]
### Astro Info

```block
Astro                    v4.3.5
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/netlify
Integrations             @astrojs/tailwind
```

### Describe the Bug

Currently, if you are deploying to Netlify, you have access to platform features there such as geo location information.

![CleanShot 2024-03-16 at 11 08 52](https://github.com/withastro/adapters/assets/833231/3b250f27-cd49-4235-8ec1-daeeb03fcfc5)

### What's the expected result?

I'd expect the types for `Astro.locals.netlify` to be defined.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ewmpks

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by nickytonline** [comment]
Happy to put up a PR for this. Declaration mergind is the way I'd go. I'd suggest adding the types in https://github.com/withastro/adapters/blob/main/packages/netlify/src/types.d.ts

```typescript
declare namespace App {
  export interface Locals {
    netlify: {
      context: {
        geo: {
          timezone: string
          city: string
          country: string
          latitude: number
          longitude: number
        }
      }
    }
  }
}
```

Here it is working in my local project.

![CleanShot 2024-03-16 at 11 12 29](https://github.com/withastro/adapters/assets/833231/bde98984-4a79-446a-a04d-291b246a477a)

**Comment by alexanderniebuhr** [comment]
Thanks for the report. Usually users type `Astro.locals` themselves, so I don't know if this should be done by the adapter. I'll asked others to weigh in.

**Comment by nickytonline** [comment]
The reason why I'm suggesting it is that the adapter is for a specific platform, so why not expose the types for that platform?

**Comment by alexanderniebuhr** [comment]
We discussed this on our Discord in the open channel for contribution. For the time being we do recommend typing manually. But there is a interface you can extend, which is documented here: (https://docs.astro.build/en/guides/integrations-guide/netlify/#accessing-edge-context-from-your-site)

We faced some limitations in the past with your suggested approach, but will look into this in the future again.

**Comment by alexanderniebuhr** [comment]
I'm closing this issue, since our position has not changed. If anything changes, we can reopen this in the future :)
