### ISSUE TITLE
API routes are not recognised using Netlify Adapter

### ISSUE THREAD

**Issue by whitep4nth3r** [withastro/adapters#2]
I was following [this recipe](https://docs.astro.build/en/recipes/build-forms-api/) when using the Netlify Adapter.

When using the Netlify CLI and deploying to Netlify, the API route is not recognised.

A little bit of debugging by @estephinson suggests that the API route is treated as an asset.

**Comment by matthewp** [comment]
That is pretty odd @estephinson, thanks for the investigation work.

**Comment by matthewp** [comment]
I was able to get it to work with this example: https://github.com/matthewp/astro-netlify-example-1

Only change from the recipe is that I added a netlify.toml. Without that it wasn't able to find any routes. This doesn't sound like the same thing you ran into @whitep4nth3r 

Would you mind providing some of the output of the function log? It should be in `https://app.netlify.com/sites/YOUR_SITE/logs/functions/entry`. The output after you attempt to hit the API is what we want.

Another thing to check, you are using `POST` for the form submission right? Without that you would get a 404.

**Comment by whitep4nth3r** [comment]
Here's the code I'm trying to run: https://github.com/whitep4nth3r/findsomethingtodo/blob/main/src/pages/api/add-todo.js

Here are the logs I get (on the Netlify CLI) when I submit the form on port 8888.

```
 ›   Warning: Missing form submission function handler
Request from ::1: POST /api/add-todo
Response with status 404 in 2 ms.
 ›   Warning: Missing form submission function handler
Request from ::1: POST /api/add-todo.html
Response with status 404 in 1 ms.
 ›   Warning: Missing form submission function handler
Request from ::1: POST /api/add-todo.htm
Response with status 404 in 0 ms.
 ›   Warning: Missing form submission function handler
Request from ::1: POST /api/add-todo/index.html
Response with status 404 in 0 ms.
 ›   Warning: Missing form submission function handler
Request from ::1: POST /api/add-todo/index.htm
Response with status 404 in 1 ms.
```

And what I've just noticed, is that when running the project with the Netlify CLI and using port 4321 in the browser, the form works.

The issue is, the Netlify CLI automatically opens a browser window on port 8888 — so I've always been inclined to use that by default.

On a live deployed site, it works as expected. (I admit I didn't deploy it before, and assumed that given it wasn't working using the Netlify CLI, it wouldn't work on a live deployment.)

I think this is reminiscent of an issue I submitted to the Netlify CLI a while ago about port number confusions: https://github.com/netlify/cli/issues/5433

**Comment by alexanderniebuhr** [comment]
Can we confirm that this is still an issue.

**Comment by whitep4nth3r** [comment]
It's an issue with the Netlify CLI, and not Astro. So this can be closed.
