### ISSUE TITLE
Cloudflare build output changes response headers and doesn't log

### ISSUE THREAD

**Issue by sjunepark** [withastro/adapters#221]
### Astro Info

```block
Astro                    v4.5.14
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             none
```

### Describe the Bug

Hi, I'm not 100% sure these are bugs or just skill issues, but have noticed the problems below which I couldn't figure out why. 

In **`astro dev` everything seems to work fine**, but the `wrangler pages dev dist` version and the actual cloudflare deployed versions have the problem below.

```ts
// src/pages/greet.ts
import type { APIRoute } from 'astro'

export const GET: APIRoute = () => {
    console.log("Shouldn't this be logged?")
    return new Response(
        JSON.stringify({
            greeting: 'Hello',
        }),
        {
            headers: {
                'content-type': 'application/json',
            },
        }
    )
}
```

1.  The endpoint returns header of `'content-type': 'application/octet-stream'`
2. The `console.log` doesn't log anything to the console. (I've tried changing the [--log-level](https://developers.cloudflare.com/workers/wrangler/commands/#dev) during `wrangler pages dev` but this doesn't seem to be the issue.

Here is a simple reproduced [repo](https://github.com/sjunepark/astro-cf-reproduce) for this, thanks.

### What's the expected result?

1.  The endpoint should returns header of `'content-type': 'application/json'` as specified in the source code.
2. The `console.log` should be logged

### Link to Minimal Reproducible Example

https://github.com/sjunepark/astro-cf-reproduce

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dallyh** [comment]
Hello, you're using hybrid output mode, that means all of the routes are prerendered by default. Try adding `export const prerender = false` to the greet endpoint.

**Comment by sjunepark** [comment]
@dallyh Glad this was my issue, thank you so much!
