### ISSUE TITLE
Hybrid Cloudflare build fails with 'Uncaught TypeError: Iterator value undefined is not an entry object'

### ISSUE THREAD

**Issue by ekojsalim** [withastro/adapters#245]
### Astro Info

```block
Astro                    v4.6.3
Node                     v20.10.0
System                   Linux (x64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/sitemap
```

### Describe the Bug

Building the project is successful but running the Wrangler preview results in this error. 

```
✘ [ERROR] service core:user:worker: Uncaught TypeError: Iterator value undefined is not an entry object

    at null.<anonymous> (nr2amrcapis.js:10399:15)


✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
```

Likely the same issue as @lokmanm [reported here](https://github.com/withastro/adapters/issues/237#issuecomment-2068073492). Downgrading to `"@astrojs/cloudflare": "10.1.0"` seems to resolve this, maybe still a regression leftover not fixed by #238.

I've provided a [minimal reproduction](https://github.com/ekojsalim/astro-iterator-repro) below. This bug appears to happen when there are 2 routes with one having `export const prerender = true;`.

### What's the expected result?

The Wrangler preview to be working.

### Link to Minimal Reproducible Example

https://github.com/ekojsalim/astro-iterator-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
Yeah thanks, that is a leftover, a fix is pending. Thanks for the example!
