### ISSUE TITLE
Cloudflare build error with `astro/lit` SSR

### ISSUE THREAD

**Issue by tkd-yas** [withastro/adapters#262]
### Astro Info

```block
Astro                    v4.8.2
Node                     v20.4.0
System                   macOS (arm64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/lit
```

### Describe the Bug

I faced build error on Cloudflare pages.
The target app is Astro integrated lit.

Error Message:
```
Error: Failed to publish your Function. Got error: Uncaught Error: No such module "@astrojs/lit/server.js".
  imported from "renderers.mjs"
```
[full logs](https://github.com/withastro/astro/files/15328076/astro-lit-cloudflare.07e92845-b1df-435c-9e2d-e4df0b4dff1a.log)

Cause is generated renderers.mjs includes unexists import.
```
import _renderer0 from '@astrojs/lit/server.js';
```

i think avoid this external file load.
anyone knows work around?

### What's the expected result?

success buid on Cloudflare Pages.

### Link to Minimal Reproducible Example

https://github.com/tkd-yas/astro-lit-cloudflare

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
@matthewp Using Node APIs might be a blocker, but the first blocker we face here is that we set it to be externalized: https://github.com/withastro/astro/blob/main/packages/integrations/lit/src/index.ts#L17

As long as it is externalized we can't use it with Astro, I think the initially question is, could we not have that setting in the package? 🤔

**Comment by matthewp** [comment]
It may not need to be external any more. That's like pretty old code.

**Comment by alexanderniebuhr** [comment]
This should be fixed in the v11 release, which will be published later today to npm.

**Comment by a-xmd** [comment]
Was this fixed in he v11 release? I'm still getting:

> Error: Failed to publish your Function. Got error: Uncaught Error: No such module "@astrojs/lit/server.js".
>   imported from "renderers.mjs"

Minimal Reproducible Example: https://github.com/a-xmd/astro-lit-cloudflare-repro

[Full log](https://github.com/user-attachments/files/16636527/astro-lit-cloudflare-repro.940bbf09-6c74-4aa1-bfcd-41a74f4c026a.log)
