### ISSUE TITLE
Can't Build Starlight project with Cloudflare adapter

### ISSUE THREAD

**Issue by tsavpyn** [withastro/adapters#279]
### What version of `starlight` are you using?

0.23.1

### What version of `astro` are you using?

4.9.2

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Edge Chromium

### Describe the Bug

I expected to use Supabase for authentication on my Starlight site, and followed the instruction from [Supabase & Astro | Docs](https://docs.astro.build/en/guides/backend/supabase) in which said that an Astro project with SSR enabled is required. 

I deployed my project to Cloudflare Pages before so certainly I followed the instructions and configured @astrojs/cloudflare for SSR feature correctly. Also I have noticed that node.js is not supported in Cloudflare SSR so I also did the compatible jobs given by both Cloudflare Docs and Astro Docs. 

Unexpected that I still got errors after that, I ran `npm run build` and received errors as below: 
```
[GenerateContentTypesError] `astro sync` command failed to generate content collection types: filename.split is not a function
  Hint:
    Check your `src/content/config.*` file for typos.
  Error reference:
    https://docs.astro.build/en/reference/errors/generate-content-types-error/
  Stack trace:
    at syncContentCollections (file:///C:/Users/makarov/WebstormProjects/rookies/node_modules/astro/dist/core/sync/index.js:110:11)
    at async AstroBuilder.run (file:///C:/Users/makarov/WebstormProjects/rookies/node_modules/astro/dist/core/build/index.js:162:23)
    at async build (file:///C:/Users/makarov/WebstormProjects/rookies/node_modules/astro/dist/cli/build/index.js:20:3)
    at async cli (file:///C:/Users/makarov/WebstormProjects/rookies/node_modules/astro/dist/cli/index.js:168:5)
  Caused by:
  filename.split is not a function
    at normalizePath (file:///C:/Users/makarov/WebstormProjects/rookies/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:2725:21)
    at Object.test (file:///C:/Users/makarov/WebstormProjects/rookies/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:2749:33)
    at file:///C:/Users/makarov/WebstormProjects/rookies/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:49941:34
    at shouldExternalizeForSSR (file:///C:/Users/makarov/WebstormProjects/rookies/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:49879:12)        
    at Array.map (<anonymous>)
``` 

I have no idea how and why. I regard this as a bug that is unexpected to appear. Is Starlight not compatible with SSR mode? 
Or is there any way else that I can use Supabase authentication without enabling SSR mode? 

Really appreciate it if this could be solved. 

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/starlight/tree/main/examples/basics?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
@tsavpyn I don't know where you found the settings for your `astro.config.mjs`, but I'm pretty sure those are not right.

Use the following please:

```diff
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

import cloudflare from '@astrojs/cloudflare';

// https://astro.build/config
export default defineConfig({
  integrations: [
    starlight({
      title: 'My Docs',
      social: {
        github: 'https://github.com/withastro/starlight',
      },
      sidebar: [
        {
          label: 'Guides',
          items: [
            // Each item here is one entry in the navigation menu.
            {
              label: 'Example Guide',
              link: '/guides/example/',
            },
          ],
        },
        {
          label: 'Reference',
          autogenerate: {
            directory: 'reference',
          },
        },
      ],
    }),
  ],
-  output: 'server',
+  output: 'hybrid',
  adapter: cloudflare({}),
-  vite: {
 -   ssr: {
  -    noExternal: false,
  -  },
 - },
});
```

**Comment by tsavpyn** [comment]
> @tsavpyn I don't know where you found the settings for your , but I'm pretty sure those are not right. I also don't see any other reason why the issue would be adapter specific, since it fails in a core file. should be and the vite settings shouldn't be included. So change them as follow please:`astro.config.mjs``output``hybrid`
> 
> ```diff
> import { defineConfig } from 'astro/config';
> import starlight from '@astrojs/starlight';
> 
> import cloudflare from '@astrojs/cloudflare';
> 
> // https://astro.build/config
> export default defineConfig({
>   integrations: [
>     starlight({
>       title: 'My Docs',
>       social: {
>         github: 'https://github.com/withastro/starlight',
>       },
>       sidebar: [
>         {
>           label: 'Guides',
>           items: [
>             // Each item here is one entry in the navigation menu.
>             {
>               label: 'Example Guide',
>               link: '/guides/example/',
>             },
>           ],
>         },
>         {
>           label: 'Reference',
>           autogenerate: {
>             directory: 'reference',
>           },
>         },
>       ],
>     }),
>   ],
> -  output: 'server',
> +  output: 'hybrid',
>   adapter: cloudflare({}),
> -  vite: {
> -    ssr: {
> -      noExternal: false,
> -    },
> -  },
> });
> ```

Thanks for reply, but the way you provided is obviously tried and not working. 
The reason I added `vite` setting is that without `vite.ssr.noExternal = false` option, it will give errors when running `npm run build`, and it will ask you to add `vite.ssr.noExternal = false` into the config. 
`hybrid` and `server` modes are both tried and came into the same result.

**Comment by alexanderniebuhr** [comment]
We have documentation about that https://docs.astro.build/en/guides/integrations-guide/cloudflare/#nodejs-compatibility. You need to add those manually to be external to hide the warning, but be warned it doesn't mean those Node.js APIs are supported by Cloudflare, but the last time I checked starlight doesn't use them in runtime only during build.
There is a open PR on Starlight which, once released, will fix the need for manually adding that settings. But @delucis could give more information on timing for that :)

**Comment by tsavpyn** [comment]
> We have documentation about that https://docs.astro.build/en/guides/integrations-guide/cloudflare/#nodejs-compatibility. The message you see is from vite and not us, so the proposed solution is not correct for Cloudflare. You need to add those manually to be external to hide the warning, but be warned it doesn't mean those Node.js APIs are supported by Cloudflare, but the last time I checked starlight doesn't use them in runtime only during build.
> There is a open PR on Starlight which, once released, will fix the need for manually adding that settings. But @delucis could give more information on timing for that :)

Yes certainly I've checked almost every doc about Cloudflare Node.js compatibility, like adding a compatibility mark to the dashboard and configuring as in the @astrojs/cloudflare document. Unfortunately none of these work, that's why I think it is a bug. 

Thank you again for your patience and hard work. Do you mean that I just need to follow up with further updates of Starlight, or there is something more I should do such as provide more info? 

Happy building! :)

**Comment by alexanderniebuhr** [comment]
The error you posted in a comment earlier is described in the docs link and following the steps outlined there, fixes the issue. If you have still another issue after that, it would be great if you can tell us where we can reproduce them inside your example?

**Comment by tsavpyn** [comment]
Group,

Thanks for everyone's help, I really appreciate that. 
The Cloudflare adapter issue I met is solved, I think, just waiting for built-in Starlight SSR support. 
Happy building! This issue is now closed. ☺️🤩
