### ISSUE TITLE
Bug Report: Unable to Destructure 'env' Property from 'Astro2.locals.runtime'

### ISSUE THREAD

**Issue by lowinn** [withastro/adapters#287]
### Astro Info
 - Version 4.10.2
 - adapter : cloudflare
 - node : v20.11.1
 - OS linux ( https://idx.google.com/ )
 - output : server
 - package manager : yarn 4.2.2
 - Integrations: [tailwind, sitemap, sanity, sentry, react, mdx, AstroPWA]

      ### Middleware code :
      `export function GET(context) {
    const runtime = context.locals.runtime;
  
    return new Response('Some body');
  }`

```block
yarn dev

 ⛅️ wrangler 3.60.2
-------------------

interface Env {
        MY_VARIABLE: "test";
        DB_PASSWORD: string;
}

02:08:23 [WARN] [config] The feature "astro:env getSecret" is experimental and subject to change (used by @astrojs/cloudflare).
02:08:23 [types] Added src/env.d.ts type declarations.

 astro  v4.10.2 ready in 2534 ms

┃ Local    http://localhost:8002/
┃ Network  http://XXXXXXXXX:8002/

02:08:24 watching for file changes...
02:08:42 [ERROR] Cannot destructure property 'env' of 'Astro2.locals.runtime' as it is undefined.
```

### Describe the Bug

When attempting to destructure the 'env' property from the 'Astro2.locals.runtime' object, an error occurs stating that the property is undefined. This prevents the expected behavior of the code and hinders its functionality.

### What's the expected result?

The 'env' property should be properly defined within the 'Astro2.locals.runtime' object and should be successfully destructured without encountering any errors.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-4gxv2t?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
@lowinn you need to enable the support for `astro dev` manually. 

```diff
import { defineConfig } from 'astro/config';
import cloudflare from '@astrojs/cloudflare';

export default defineConfig({
  output: 'server',
+  adapter: cloudflare({
+    platformProxy: {
+      enabled: true
+    }
+  }),
});

```

**Comment by lowinn** [comment]
> @lowinn you need to enable the support for `astro dev` manually. _It will be enabled by default with the next major version._
> 
> ```diff
> import { defineConfig } from 'astro/config';
> import cloudflare from '@astrojs/cloudflare';
> 
> export default defineConfig({
>   output: 'server',
> +  adapter: cloudflare({
> +    platformProxy: {
> +      enabled: true
> +    }
> +  }),
> });
> ```

@alexanderniebuhr @ematipico @OliverSpeir Thank you guys it's work now.
