### ISSUE TITLE
Cloudflare build fails when using experimental env vars (rollup failed to resolve import "astro:env/client")

### ISSUE THREAD

**Issue by jkhaui** [withastro/adapters#306]
### Astro Info

```block
Astro                    v4.11.1
Node                     v20.6.1
System                   Windows (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             my-astro-integration
                         @qwikdev/astro
                         astro-react-navigation
                         @astrojs/tailwind
                         @astrojs/sitemap
                         @playform/compress
```

### Describe the Bug

Hi,

I saw the cloudflare adapter had a major update, so I read the [changelog](https://github.com/withastro/adapters/blob/main/packages/cloudflare/CHANGELOG.md) and noticed there appears to be a push to use the experimental env vars option. So I've followed the instructions and my dev environment works fine.

But when deploying to CF, I get the following error about rollup failing to resolve `astro:env/client`:

![image](https://github.com/withastro/astro/assets/36477474/b9e71288-db90-4638-af6c-2a953c95eae5)

Then, I follow the workaround to externalise it, and now I get this error:

![image](https://github.com/withastro/astro/assets/36477474/fb0b6d28-541f-4ca6-ad5e-c89e891dfb07)

No idea what to do - is this a Cloudflare issue, an actual bug, or am I just overlooking something really obvious?
Btw, I know the Astro team is great and works hard to support many runtimes, use-cases, etc. but boy I've probably spent more time trying to get project configuration & environment variables working in dev vs. prod than actually developing my app

### What's the expected result?

Env vars should work in production

Sorry for not providing a proper repo, it's just not feasible considering we're dealing with a CF build pipeline issue

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/basics?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
I wish I could help on that one for `astro:env` but i know very little about how cloudflare works so i'll wait for Alex's opinion first

**Comment by alexanderniebuhr** [comment]
Happy to reopen this issue, when a reproduction is provided.
