### ISSUE TITLE
[commonjs--resolver] [plugin vite:resolve] Cannot bundle Node.js built-in "module" imported 

### ISSUE THREAD

**Issue by cpxGithub** [withastro/adapters#308]
### Astro Info

```block
Astro                    v4.11.3
Node                     v22.2.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             astro-i18next
```

### Describe the Bug

1. Use astro-i18next to configure website internationalization
2. Use @astrojs/cloudflare as server-side rendering adapter
3. When using the build command, the following error message is displayed:
![截屏2024-06-27 19 07 07](https://github.com/withastro/adapters/assets/20429937/5f8adf1f-06f2-4c18-91ad-01b67db2ffca)

### What's the expected result?

build success

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-habvmy

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
Looks like astro-i18n-next uses Node.js APIs, which are not supported by Cloudflare.

**Comment by alexanderniebuhr** [comment]
If any new informations are available, I'm happy to reopen this issue.
