### ISSUE TITLE
cloudflare adapter breaks rollupOptions output filenames

### ISSUE THREAD

**Issue by mschoeffmann** [withastro/adapters#334]
### Astro Info

```block
Astro                    v4.12.2
Node                     v20.14.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

Using rollupOptions like entryFileNames, chunkFileNames and assetFileNames for reasons (withastro/astro#7469, withastro/astro#8549, withastro/astro#5787, ...) moves the files from `./dist` folder to `./dist/_render.js` which results in 404 after deploying.

```javascript
      rollupOptions: {
        output: {
          entryFileNames: '_static/entry.[hash].js',
          chunkFileNames: '_static/chunk.[hash].js',
          assetFileNames: '_static/asset.[hash][extname]',
        },
      },
```

check out the min. reproduction stackblitz and run the command `npm run build` first with the above config, and second with the above lines commented out. there it only affects the .css file but on larger projects it affects all bundled chunks and assets.

not working: css is _worker.js subfolder:
<img width="407" alt="Screenshot 2024-07-20 at 02 35 00" src="https://github.com/user-attachments/assets/94dd7c7f-692a-4a79-b7ff-d150b4598550">

working without output filename config: css is in _astro subfolder:
<img width="407" alt="Screenshot 2024-07-20 at 02 35 45" src="https://github.com/user-attachments/assets/a641cc9c-e430-4689-a0c7-259115a8c6f9">

### What's the expected result?

bundled files in `./_static` as configured. works without adapter and `'static'` output mode.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tzkvup?file=src%2Flayouts%2FLayout.astro%2Castro.config.mjs&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

_Changes:_ edited screenshot annotations and fixed issue links

**Comment by alexanderniebuhr** [comment]
@mschoeffmann Thank you for the report. Is this `'dist/_static/chunk.[hash].js'` you expected output path?

If so I'm afraid that it won't be supported, since all SSR related files must be under the path `'dist/_worker.js'/`

**Comment by alexanderniebuhr** [comment]
Okay understood. I don't think it would be working with chunks. Only static assets like css, etc.

I also think their is a different configuration for that, let me see if I can find it.

**Comment by alexanderniebuhr** [comment]
I'll try to see if the same behavior happens with the Node adapter, to see if this is a core issue.

**Comment by matthewp** [comment]
It's pretty unlikely that this is going to work. Netlify and Vercel need files to be in special folders for their deployment. It's not really configurable.

**Comment by alexanderniebuhr** [comment]
The node adapter has the same issue when using `build.server` & `build.client`: https://stackblitz.com/edit/github-tzkvup-oqmfkz?file=astro.config.mjs

**Comment by alexanderniebuhr** [comment]
@mschoeffmann Any reason why you can't use https://docs.astro.build/en/reference/configuration-reference/#buildassets to change the name of `_astro`, for the static assets?

**Comment by matthewp** [comment]
Overriding `vite` in your config applies to the server-side and client-side code. I think you only want client-side. So using the build.assets config option like @alexanderniebuhr suggested, or using the `astro:build:setup` hook to set options only for client-side builds is the way to go: https://docs.astro.build/en/reference/integrations-reference/#astrobuildsetup

**Comment by matthewp** [comment]
It's not really a workaround, those are the methods of adjusting output filenames for client-side code. `vite` is global configuration. Let us know if it works out!

**Comment by alexanderniebuhr** [comment]
Yeah I guess for **"2."** `build:assets: "_static"` is the correct way :)

**Comment by alexanderniebuhr** [comment]
Great to hear you found a way to solve your use-case, I'll close the issue for now.

**Comment by alexanderniebuhr** [comment]
That's great. I suggest posting this to the `showcase` channel in Discord too :)
