### ISSUE TITLE
Astro DB with Cloudflare adapter: missing app token

### ISSUE THREAD

**Issue by atej** [withastro/adapters#339]
### Astro Info

```block
Astro                    v4.12.2
Node                     v20.16.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/react
                         astro:db
                         @astrojs/db/file-url
                         astro-icon
```

### Describe the Bug

With rendering mode (output) set to 'server', the build (`astro build --remote`) completes, but the worker fails to start. The `ASTRO_STUDIO_APP_TOKEN` secret has been set appropriately via the Cloudflare settings dashboard.

```
service core:user:worker: Uncaught Error: Cannot create a remote client: missing app token.
at null.<anonymous> (edqka0k952.js:7540:11) in createRemoteDatabaseClient
```

Changing to `output: 'hybrid'` resolves this.

The same behaviour can be observed via `wrangler pages dev` (secret set in `.dev.vars`)

This issue has been previously referenced here: https://github.com/withastro/astro/issues/10668#issuecomment-2198512038

### What's the expected result?

Should work with both 'server' and 'hybrid' rendering modes.

### Link to Minimal Reproducible Example

https://stackblitz.com

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
Please provide a minimal reproduction

**Comment by atej** [comment]
> Please provide a minimal reproduction

Even a "minimal" reproduction would take a lot of setup.  A new Astro Studio project with a`ASTRO_STUDIO_APP_TOKEN`, a new Cloudflare account, everything authenticated via CLI or GitHub, etc.

**Comment by alexanderniebuhr** [comment]
You don't need all of that, we can provide Astro, Studio, Tokens, Cloudflare Account, and the deployment ourselves, but we would need to get the minimal production for the code from you, because we need to see in which Files you are using `astro:db` and how you are using the env vars.

**Comment by alexanderniebuhr** [comment]
I'm happy to reopen this issue if we have an reproduction.
