### ISSUE TITLE
[cloudflare] context.locals.runtime.ctx undefined when running astro build

### ISSUE THREAD

**Issue by mlafeldt** [withastro/adapters#365]
### Astro Info

```
Astro                    v4.14.5
Node                     v22.7.0
System                   macOS (arm64)
Package Manager          bun
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @clerk/astro/integration
                         @astrojs/tailwind
```

### Describe the Bug

While adding middleware for Astro on Cloudflare Pages, I noticed that the Cloudflare adapter does not define `context.locals.runtime.ctx` when running `astro build`.

This requires the following workaround, as discussed in https://github.com/getsentry/sentry-javascript/issues/13217

```ts
const sentry = defineMiddleware((context, next) => {
  const { ctx, env } = context.locals.runtime

  // Sentry needs ctx.waitUntil, which works at runtime but isn't defined when running `astro build`
  if (!ctx) {
    return next()
  }

  return Sentry.wrapRequestHandler(
    {
      options: {
        dsn: env.SENTRY_DSN,
        environment: import.meta.env.MODE,
      },
      request: context.request,
      context: ctx,
    },
    () => next()
  )
})
```

Another weirdness is that `context.locals.runtime.env` will include OS env vars with `astro build`, while it will only contain the variables from `wrangler.toml` and `.dev.vars` with `astro dev`. This leads to the unfortunate situation where you sometimes have to define env vars twice (build time + runtime) for some middlewares to work.

### What's the expected result?

`context.locals.runtime.ctx` and `context.locals.runtime.env` behave the same at build time and runtime, so that middleware can work in both cases

### Link to Minimal Reproducible Example

https://github.com/getsentry/sentry-javascript/issues/13217

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by mlafeldt** [comment]
I wonder if it's even possible to inject stuff at build time given that the `astro:build:setup` hook doesn't take a `server` object:

https://github.com/withastro/adapters/blob/18bfd51f509419ac9789af0d0505d8d663914c65/packages/cloudflare/src/index.ts#L204

Modifying middleware seems to be limited to `astro:server:setup`, which isn't invoked by `astro build`.

https://github.com/withastro/adapters/blob/18bfd51f509419ac9789af0d0505d8d663914c65/packages/cloudflare/src/index.ts#L175-L190

**Comment by alexanderniebuhr** [comment]
As described here https://github.com/getsentry/sentry-javascript/issues/13217#issuecomment-2315350175 `astro build` doesn't run inside the Cloudflare runtime, so we can't provide the runtime specific features there.
If you rely on the middleware for prerendered and on-demand pages, the expected and "correct" way is to define the environment variables twice.

**Comment by mlafeldt** [comment]
> As described here [getsentry/sentry-javascript#13217 (comment)](https://github.com/getsentry/sentry-javascript/issues/13217#issuecomment-2315350175) `astro build` doesn't run inside the Cloudflare runtime, so we can't provide the runtime specific features there.
> If you rely on the middleware for prerendered and on-demand pages, the expected and "correct" way is to define the environment variables twice.

Got it. I wish there was a way to disable (SSR) middleware during astro build—or at least to detect that `middleware.ts` is running in that context so I can skip handlers myself. None of the middleware I use needs to do stuff at build time, and I imagine that is the case for most people using SSR in general and the Cloudflare adapter in particular.

**Comment by mlafeldt** [comment]
@alexanderniebuhr Oh, that's amazing and exactly what I needed. Thanks a lot! 🙏🚀

```ts
// Skip all middleware unless there's a server
export const onRequest = [When.Server, When.DevServer].includes(whenAmI) && sequence(sentry, clerk)
```

**Comment by alexanderniebuhr** [comment]
Just as a side-note I just found out, that Astro 5 when it comes out, should have some value in `context`, which tells you if the middleware runs for an prerendered page or not.
