### ISSUE TITLE
CloudFlare Environment Variables not populating with build (using Github CI/CD)

### ISSUE THREAD

**Issue by serdar** [withastro/adapters#369]
### Astro Info

```block
Astro                    v4.15.1
Node                     v21.5.0
System                   Linux (x64)
Package Manager          pnpm locally (npm on build server)
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             none
```

### Describe the Bug

I have an environment variable named `TESTVAR` setup in my `.env` file locally and within the Cloudflare Workers & Pages project dashboard. The variable value is retrieved from a function in the  `src/app.ts` file called from `pages/index.astro`.

I've set up Cloudflare to build and deploy using Github. However, when I push my changes to trigger the build the variable value is not populated. No errors are reported in the build log.
```
export function getCafe(): string {
  return import.meta.env.TESTVAR || process.env.TESTVAR || "DEFAULT_CAFE";
}
```

Site: https://cf-astro-2.pages.dev/

### What's the expected result?

The site is outputting the value 'DEFAULT_CAFE' whilst I was expecting the value to be pulled from the Cloudflare project setting (which is set to 'CF-PAGES-CAFE-PROD').

### Link to Minimal Reproducible Example

https://github.com/serdar/cf-astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
`import.meta.env.TESTVAR` will be replaced during build time, so it can't have access to runtime variables. The solution for that is to use `Astro.locals` or the experimental `astro:env`

**Comment by serdar** [comment]
Thanks @alexanderniebuhr - that's handy to know but in my actual repo I'm using this to retrieve a (Turso) database connection URL and token. So it's OK for it to be baked in at build time. I was a few releases behind but this was working with `"astro": "^4.10.2"` and `@astrojs/cloudflare": "9.2.1"`

**Comment by alexanderniebuhr** [comment]
I guess it's a breaking change of the adapter, it was documented in the CHANGELOG:

https://github.com/withastro/adapters/blob/main/packages/cloudflare/CHANGELOG.md#1000
https://github.com/withastro/adapters/blob/main/packages/cloudflare/CHANGELOG.md#1100

**Comment by serdar** [comment]
Switching over to the experimental `astro:env` worked, thank you.
