### ISSUE TITLE
Incorrect svelte bundle imported when using svelte 5 with CloudFlare adapter

### ISSUE THREAD

**Issue by giraugh** [withastro/adapters#410]
### Astro Info

```block
Astro                    v4.15.10
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/svelte
```

### Describe the Bug

When running and accessing a built astro app that uses svelte components and the CloudFlare workers adapter, it emits `lifecycle_outisde_component` errors. Only applies when using svelte 5.

```
[wrangler:inf] Ready on http://localhost:8788
[wrangler:inf] GET / 200 OK (16ms)
✘ [ERROR] Uncaught (in promise) Error: lifecycle_outside_component

✘ [ERROR] Uncaught (in response) Error: lifecycle_outside_component
```

From a quick investigation, it seems like the components are importing the client bundle when running in SSR. If I import and log out svelte's `onMount()` method from the component, it emits the client implementation rather than the noop implementation expected on the server. Could relate to worker import conditions?

## Details

- This issue exists both when using the provided version of `vite-plugin-svelte` (v3) and overriding the version to v4.
- Issue does not seem to occur when using svelte 4
- Issue does not seem to occur when using a different astro adapter (e.g node)

### What's the expected result?

Expected page to render as normal without errors.

### Link to Minimal Reproducible Example

https://github.com/giraugh/astro-svelte-5-cloudflare-repro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by muuvmuuv** [comment]
Rollback to this works for now:
- @astrojs/cloudflare: 11.0.4
- astro: 4.16.0

**Comment by yuto343** [comment]
This seems to have reappeared in astro@5.0.9 and @astrojs/cloudflare@12.1.0 🥲 I downgraded to 12.0.1 to work around it.
