### ISSUE TITLE
@astrojs/lit breaks @astrojs/cloudflare builds

### ISSUE THREAD

**Issue by chaffinated** [withastro/adapters#42]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Brave

### Describe the Bug

When deploying via GitHub, the astro project builds successfully, but fails at deploying the CF function.

No lit components are used in the project; simply adding lit to the integrations field in the config seems to break deployments.

The error from Cloudflare:
`Error: Failed to publish your Function. Got error: Uncaught ReferenceError: window is not defined at functionsWorker-xxxx.js:2140:10`

A snippet of what could be the offending code in the build:
```js
var ea = window,
  aa =
    ea.ShadowRoot &&
    (ea.ShadyCSS === void 0 || ea.ShadyCSS.nativeShadow) &&
    "adoptedStyleSheets" in Document.prototype &&
    "replace" in CSSStyleSheet.prototype,
  Fn = Symbol(),
  Sn = new WeakMap(),
  ta = class {
    constructor(t, a, u) {
      if (((this._$cssResult$ = !0), u !== Fn))
        throw Error(
          "CSSResult is not constructable. Use `unsafeCSS` or `css` instead.",
        );
      (this.cssText = t), (this.t = a);
    }
    get styleSheet() {
...
```

This is apparently from the Lit library itself.

I'll keep digging in to see what I can find out, but I'd greatly appreciated any help!

### Link to Minimal Reproducible Example

https://github.com/chaffinated/astro-lit-cloudflare-repro

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
Can we confirm that this is still an issue.

**Comment by alexanderniebuhr** [comment]
Closing because it is stale & superseded by https://github.com/withastro/adapters/issues/56
