### ISSUE TITLE
[middleware] [edge] [netlify] adapter option `edgeMiddleware: true` is not (no longer?) compatible with astro custom middleware.

### ISSUE THREAD

**Issue by PaulSenon** [withastro/adapters#483]
### Astro Info

```block
Astro                    v5.0.5
Node                     v20.18.1
System                   Linux (arm64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/netlify@6.0.0
```

### Describe the Bug

When you have a custom [Astro middleware](https://docs.astro.build/en/guides/middleware/) in your project and you try to deploy to Netlify with the `@astrojs/netlify@6.0.0` option flag `edgeMiddleware` set to `true` it causes a runtime error at the edge:

<img width="895" alt="image" src="https://github.com/user-attachments/assets/575a80b3-d67d-40f4-9e75-a660fc5107a3" />

Edge Function log:
```shell
Dec 14, 03:39:13 PM: 01JF1Y91 info   [Astro Middleware] LocalsReassigned: `locals` can not be assigned directly.
    at Object.set locals (file:///root/.netlify/v1/edge-functions/middleware/middleware.mjs:3223:13)
    at entry_default (file:///root/.netlify/v1/edge-functions/middleware/middleware.mjs:3271:14)
    at file:///root/src/bootstrap/function_chain.ts:479:15
    at AsyncLocalStorage.run (node:async_hooks:69:14)
    at FunctionChain.runFunction (file:///root/src/bootstrap/function_chain.ts:473:28)
    at FunctionChain.run (file:///root/src/bootstrap/function_chain.ts:344:31)
    at file:///root/src/bootstrap/function_chain.ts:395:12
    at new Promise (<anonymous>)
    at FunctionChain.runWithSignal (file:///root/src/bootstrap/function_chain.ts:388:12)
    at handleRequest (file:///root/src/bootstrap/handler.ts:175:36) {
  loc: undefined,
  title: "`locals` must not be reassigned.",
  hint: "Set a `locals` property instead.",
  frame: undefined,
  type: "AstroError",
  name: "LocalsReassigned"
}
```

## First idea

It looks like the adapter part writing the edge middleware function for netlify tries to merge both the default netlify middleware and custom ones. But it does something illegal from Astro perspective by redefining the context.local object.

I tries to patch the astro adapter on my side by removing this illegal reasign, and it kinda work (no longer crashing, and I can see my custom middleware logs in the Netlify Edge Log pannel. But it's not fully working as setting any `context.locals` props in my custom middleware is not doing anything (they might be stuck at some point of the process)

I can see in the adapter code that it does something related to pass the custom Astro.locals values via some custom header, but I don't have the big picture of the process underneath and struggle to properly fix it.

Here is where in the code of the custom adapter I am talking about (highlighted lines)
<https://github.com/withastro/adapters/blob/9d98b8a19efdd5c7483cce70b732208093bf82b2/packages/netlify/src/index.ts#L289C4-L321C33>

### Test Configurations:

| Test Name | Static | Edge Middleware Option | Custom Middleware |
|--------|------|----------------|------------------|
| `1-target`      | ✅ static | ✅ true | ✅ Present |
| `2-no-edge`      | ✅ static | ❌ false | ✅ Present |
| `3-no-middleware`      | ✅ static | ✅ true | ❌ Absent |
| `4-not-static`      | ❌ server | ✅ true | ✅ Present |

when I say `Static` or `Server` mode I mean:
```
// astro.config.mjs

export default defineConfig({
        // ...
	output: 'static', // or 'server'
        // ...
});
```

when I say `Edge Middleware` I mean:
```
// astro.config.mjs

export default defineConfig({
	// ...
	adapter: netlify({
		edgeMiddleware: true, // <<<
	}),
	// ...
});
```

when I say `Custom Middleware` I mean the presence of a `src/middleware.ts` file ([Astro middleware](https://docs.astro.build/en/guides/middleware/))

### Test Results:

| Test Name | Working | Expected |
|--------|---------|---------|
| `1-target`     | ❌ Edge Error | ✅ |
| `2-no-edge`     | ✅ Yes | ✅ |
| `3-no-middleware`     | ⚠️ Missing middleware but working without it | ⚠️ |
| `4-not-static`      | ❌ Edge Error | ✅ |

### What's the expected result?

When deploying an Astro v5 project using [server-islands](https://docs.astro.build/en/guides/server-islands/) and [custom middleware](https://docs.astro.build/en/guides/middleware/) to Netlify using `@astrojs/netlify@6.0.0` adapter and with the following Astro config:

```javascript
// astro.config.mjs

import { defineConfig } from 'astro/config';
import netlify from '@astrojs/netlify';

export default defineConfig({
    // ...
    output: 'static',
    adapter: netlify({
        edgeMiddleware: true,
    }),
    // ...
});
```

It should not raise any runtime error and give access to 
* default netlify cdn `context` object in `Astro.locals.netlify`
* custom locals in `Astro.locals`  set via `context.locals.myLocal = 123` in a custom `src/middleware.ts` like the following basic example:

```typescript
import { defineMiddleware } from "astro/middleware";

export const onRequest = defineMiddleware((context, next) => {
    context.locals.myLocal = Math.random() * 1000;
    return next();
}) 
```

So the following demo astro server component (island) should display dynamic values from these two locals source:
```astro
---
// src/components/DemoComponent.astro

export const prerender = false;

// extract one value from custom middleware
const { myLocal } = Astro.locals;
// extract one value from astro default middleware
const { requestId } = Astro.locals.netlify.context;
---

<p>{myLocal}</p>
<p>{requestId}</p>
```
When injected anywhere as
```jsx
<DemoComponent server:defer />
```

### Link to Minimal Reproducible Example

https://github.com/PaulSenon/issue-reproduction-astro-netlify-adapter

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
This will be fixed in the next release 

Closed by https://github.com/withastro/adapters/pull/481
