### ISSUE TITLE
Typing Astro.locals for Cloudflare runtime

### ISSUE THREAD

**Issue by Trildar** [withastro/adapters#55]
### 📚 Subject area/topic

Cloudflare adapter

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/integrations-guide/cloudflare/#access-to-the-cloudflare-runtime

### 📋 General description or bullet points (if proposing new content)

The documentation on how to add proper typing for `Astro.locals` seems incorrect. As can be seen from the error produced by running `astro check` in the reproduction: `error ts(2339): Property 'runtime' does not exist on type 'Locals'.`.

Using `declare global` instead, as in the code below, seems to work.

```typescript
/// <reference types="astro/client" />
import type { AdvancedRuntime } from '@astrojs/cloudflare';

type ENV = {
  SERVER_URL: string;
};

declare global {
  namespace App {
    interface Locals extends AdvancedRuntime<ENV> {
      user: {
        name: string;
        surname: string;
      };
    }
  }
}
```

Not sure if there was some change in TypeScript that caused this or anything. If there are no reasons the docs shouldn't be changed to the above, I can help submit a PR.

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-axxitg?file=src%2Fenv.d.ts

**Comment by alexanderniebuhr** [comment]
@Trildar thanks for the report. The docs where outdated at first, but area already corrected. Please see them here: https://docs.astro.build/en/guides/integrations-guide/cloudflare/#typing

Your solution works too, but we do suggest using the new documented one (using dynamic imports)

**Comment by james-pre** [comment]
@alexanderniebuhr, not sure if you're still maintaining this. I'm getting this error with the latest `@astrojs/cloudflare` and `astro`. I've tried using both the dynamic import method (from the docs) and the ESM-style imports from @Trildar's solution. You can see the complete code here: https://github.com/iit-a-star/journey/tree/e82974cd9a1dadc2002d2535a1052d415d136ba8.
