### ISSUE TITLE
Netlify adapter throws error with output: "server"

### ISSUE THREAD

**Issue by teddybee** [withastro/adapters#59]
### Astro Info

```block
Astro                    v3.5.2
Node                     v20.9.0
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/netlify
Integrations             @astrojs/tailwind
```

### Describe the Bug

It throws an error if the  output: "server"  set in the astro.config.
"static" and "hybrid" mode works well.
```
Nov 10, 11:54:05 PM: 2023-11-10T22:54:05.604Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Error","errorMessage":"Cannot find package '@astrojs/netlify' imported from /var/task/.netlify/functions-internal/entry.mjs","code":"ERR_MODULE_NOT_FOUND","stack":["Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@astrojs/netlify' imported from /var/task/.netlify/functions-internal/entry.mjs","    at new NodeError (node:internal/errors:405:5)","    at packageResolve (node:internal/modules/esm/resolve:895:9)","    at moduleResolve (node:internal/modules/esm/resolve:988:20)","    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:939:12)","    at defaultResolve (node:internal/modules/esm/resolve:1181:79)","    at nextResolve (node:internal/modules/esm/loader:163:28)","    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)","    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)","    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)","    at link (node:internal/modules/esm/module_job:76:36)"]}Nov 10, 11:54:05 PM: INIT_REPORT Init Duration: 212.75 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
```

### What's the expected result?

Start working on netlify.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-o3ve7p?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
Thank you for your report. Can you clarify when you see the error?. Looking at the example, it seems to work fine with `npm run dev` & `npm run build`

**Comment by teddybee** [comment]
@alexanderniebuhr  When I upload the app to netlify and trying the url in the browser.

**Comment by lilnasy** [comment]
Just tried it and it I can confirm the issue.
[Preview](https://655393322648e5007910a942--bespoke-gumdrop-44a21e.netlify.app/)

**Comment by lilnasy** [comment]
Affects windows only. Seems to be an issue for `netlify-cli`, since it is it's [responsibility](https://cli.netlify.com/commands/deploy#unbundled-nodejs-functions-that-have-dependencies-outside-or-inside-of-the-functions-folder) to include `node_modules` folder.

Reproduction steps:
```bash
mkdir x && cd x
pnpm create astro --template basics --yes .
pnpm astro add netlify --yes
pnpm add -D netlify-cli
pnpm astro build
pnpm netlify login
pnpm netlify deploy --dir dist
 ```
[Preview link when followed on Windows](https://655393322648e5007910a942--bespoke-gumdrop-44a21e.netlify.app/)
[Preview link when followed on Linux](https://6553aabef7e9990377b257ae--bespoke-gumdrop-44a21e.netlify.app/)

**Comment by codemonkeynorth** [comment]
can confirm this is a `pnpm` issue . 

it works fine with `npm install` => `netlify build` => `netlify deploy`
