### ISSUE TITLE
fix edge-case in `_routes.json` generation

### ISSUE THREAD

**Issue by alexanderniebuhr** [withastro/adapters#64]
- related to https://github.com/withastro/adapters/issues/67
- information about this issue on main repo

**Comment by alexanderniebuhr** [comment]
https://discord.com/channels/595317990191398933/1174021841023664288

**Comment by lilnasy** [comment]
Ran some previews to single out the configurations/defaults that make `index.astro` render for unrouted paths.

Shared in a PR comment here: https://github.com/withastro/adapters/pull/66#discussion_r1394960160
