### ISSUE TITLE
A different D1 database is created when there is already a migrated D1 database

### ISSUE THREAD

**Issue by sor4chi** [withastro/adapters#65]
### Astro Info

```block
Astro                    v3.5.4
Node                     v18.16.1
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             none
```

### Describe the Bug

please run `local migrate -> dev -> press add user button`

### What's the expected result?

`D1_ERROR: no such table: user` does not occer

### Link to Minimal Reproducible Example

https://github.com/sor4chi/repro-astro-cloudflare-d1

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
@sor4chi I think it is a configuration error, following (https://developers.cloudflare.com/d1/learning/local-development/#develop-locally-with-pages) your `wrangler.toml should look like:

```
name = "maximum-course"
compatibility_date = "2023-06-14"

[[d1_databases]]
binding = "DB"
database_name = "course-db"
database_id = "e06fe5b6-ec3a-4f18-96a8-5b94886da868"
preview_database_id = "DB"
```

**Comment by sor4chi** [comment]
hi, @alexanderniebuhr 
Wow, I've missed that! Thank you so match!
