### ISSUE TITLE
Remove deprecated features from Astro 3.0

### ISSUE THREAD

**Issue by alexanderniebuhr** [withastro/adapters#76]
We need to also make sure do check this repo for: https://github.com/withastro/astro/pull/9168

**Comment by vasfvitor** [comment]
I stumbled upon this: `type EndpointOutput` was removed.
https://github.com/withastro/astro/commit/cdabf6ef02be7220fd2b6bdcef924ceca089381e#diff-cec1de65bb8dd2f8330cb37fe3698afd66162bc0f311aa11e0b3dd573f6a2b9f

it seems that this does the trick
```diff
- import { type APIContext, type EndpointOutput } from 'astro';
+ import { type APIContext } from 'astro';
```
```diff
- Promise<EndpointOutput | Response>
+ Promise<Response>
```
Currently `type EndpointOutput` is utilized in Cloudflare adapter as lines above. After this change all 60 tests passes, even on current Astro version

**Comment by alexanderniebuhr** [comment]
@vasfvitor would you like to open a PR with that fix?
